site_url: https://trusting-stonebraker-90e3e0.netlify.app
logo_url: https://trusting-stonebraker-90e3e0.netlify.app/icon.png

# publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/uploads
public_folder: /uploads

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'news'
    label: 'Neuigkeiten'
    label_singular: 'Neuigkeit'
    folder: 'content/news'
    create: true
    format: 'frontmatter'
    slug: '{{year}}-{{slug}}'
    # TODO: preview_path
    fields:
      - { label: 'Erstellt am', name: 'date', widget: 'datetime', date_format: true, time_format: false }
      - { label: 'Titel', name: 'title', widget: 'string', required: true }
      - { label: 'Inhalt', name: 'body', widget: 'markdown', required: false }
      - { label: 'Titelbild', name: 'featuredImage', widget: 'image', required: false, allow_multiple: false }
  - name: 'events'
    label: 'Veranstaltungen'
    label_singular: 'Veranstaltung'
    folder: 'content/events'
    create: true
    format: 'frontmatter'
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    # TODO: preview_path
    fields:
      - {
          label: 'Kategorie',
          name: 'category',
          widget: 'select',
          default: 'lesung',
          options:
            [
              { label: 'Lesung', value: 'lesung' },
              { label: 'Schullesung', value: 'schullesung' },
              { label: 'Reisefilm Vorführung', value: 'reisefilm' },
            ],
        }
      - { label: 'Titel', name: 'title', widget: 'string', required: true }
      - { label: 'Datum', name: 'date', widget: 'datetime', default: '', date_format: true, time_format: true }
      - label: 'Ort'
        name: 'location'
        widget: 'object'
        fields:
          - { label: 'Bezeichnung', name: 'label', widget: 'string', required: false }
          - { label: 'Adresse', name: 'address', widget: 'string', required: true }
          - {
              label: 'Link',
              name: 'url',
              widget: 'string',
              pattern:
                [
                  'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
                  'Muss ein valide Internetaddresse sein',
                ],
              required: false,
            }
      - { label: 'Titelbild', name: 'featuredImage', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Beschreibung', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Flyer',
          name: 'flyer',
          widget: 'file',
          media_library: { config: { multiple: true } },
          required: false,
        }
      - {
          label: 'Gallerie',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Foto', name: 'image', widget: 'image' },
        }
  - name: 'books'
    label: 'Bücher'
    label_singular: 'Buch'
    folder: 'content/books'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    # TODO: preview_path
    fields:
      - { label: 'Veröffentlicht am', name: 'publishedAt', widget: 'datetime', date_format: true, time_format: false }
      - { label: 'Titel', name: 'title', widget: 'string', required: true }
      - { label: 'Titelbild', name: 'featuredImage', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Beschreibung', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'ISBN',
          name: 'isbn',
          widget: 'string',
          pattern: ['^(?=(?:\D*\d){10}(?:(?:\D*\d){3})?$)[\d-]+$', 'Muss eine valide ISBN sein'],
          required: false,
        }
      - {
          label: 'Bestell Link',
          name: 'buyLink',
          widget: string,
          pattern:
            [
              'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
              'Muss ein valide Internetaddresse sein',
            ],
          required: false,
        }
      - {
          label: 'Rezensionen',
          label_singular: 'Rezension',
          name: 'testimonials',
          widget: 'list',
          required: false,
          summary: 'von {{fields.name}}',
          fields:
            [
              { label: 'Überschrift', name: 'headline', widget: string, required: false },
              { label: 'Zitat', name: 'qoute', widget: text, required: true },
              { label: 'Von', name: 'name', widget: 'string', required: true },
              { label: 'Datum', name: 'date', widget: 'datetime', date_format: true, time_format: false },
            ],
        }
  - name: 'reisefilme'
    label: 'Reisefilme'
    label_singular: 'Reisefilm'
    folder: 'content/reisenfilme'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}-{{year}}'
    fields:
      - { label: 'Titel', name: 'title', widget: 'string', required: true }
      - { label: 'Untertitel', name: 'subtitle', widget: 'string', required: false }
      - { label: 'Jahr', name: 'year', widget: 'number', value_type: 'int', min: 1950, required: true }
      - { label: 'Titelbild', name: 'featuredImage', widget: 'image', required: true, allow_multiple: false }
      - { label: 'Beschreibung', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Gallerie',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Bild', name: 'image', widget: 'image' },
        }
  - label: 'Einstellungen'
    name: 'settings'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
